Ticketing System.Mvc/Controllers/TicketsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Ticketing_System.Core;
using Ticketing_System.Mvc.CustomIdentityClasses;
using Ticketing_System.Mvc.Models;

namespace Ticketing_System.Mvc.Controllers
{

    [Authorize]
    public class TicketsController : Controller
    {
        // GET: Tickets
        [HttpGet]
        public ActionResult ListAll(int ProjectID = 0, int task_Type = 0, int task_status = 0, int priority=0)
        {
            if (TempData["Message"] != null)
                ViewBag.Message = TempData["Message"].ToString();
            return View(FillTaskDropDowns(ProjectID, task_status, task_Type, priority));
        }


        public CreateTaskDTO FillTaskDropDowns(int ProjectID, int task_status, int task_Type, int priority)
        {
            CustomResponse res = APICalls.Get("TasksAPI/Get?ProjectID=" + ProjectID + "&IDType=1&userid=" + User.Identity.GetUserId() + "&task_status=" + task_status + "&Task_Type=" + task_Type+"&priority="+priority);
            CreateTaskDTO objTask = new CreateTaskDTO();
            if (res.Response != null)
            {
                JavaScriptSerializer serializer1 = new JavaScriptSerializer();
                serializer1.MaxJsonLength = 1000000000;
                var uinfo = res.Response.ToString();
                objTask.TasksDTO = serializer1.Deserialize<List<TaskDTO>>(uinfo);
                CustomResponse response = APICalls.Get("projectsapi/Get?projectid=0&userid=" + User.Identity.GetUserId());
                if (response.Response != null)
                {
                    var projects = response.Response.ToString();
                    List<ProjectDTO> projectsinfo = serializer1.Deserialize<List<ProjectDTO>>(projects);
                    List<SelectListItem> objprojects = new List<SelectListItem>();
                    foreach (ProjectDTO pdto in projectsinfo)
                        objprojects.Add(new SelectListItem { Text = pdto.Name, Value = pdto.ID.ToString() });
                    if (ProjectID == 0)
                        objprojects.Insert(0, new SelectListItem { Text = "All", Value = "0", Selected = true });
                    else
                    {
                        objprojects.Insert(0, new SelectListItem { Text = "All", Value = "0", Selected = true });
                        objprojects.Find(x => x.Value == ProjectID.ToString()).Selected = true;
                    }

                    List<SelectListItem> objtasktypedata = new List<SelectListItem>();
                    List<SelectListItem> objtaskstatusdata = new List<SelectListItem>();
                    List<SelectListItem> objtaskstatusdata2 = new List<SelectListItem>();


                    CustomResponse restype6 = APICalls.Get("GenericAPI/Get?type=1");
                    if (restype6.Response != null)
                    {
                        var tasktype1 = restype6.Response.ToString();
                        List<TypeAndPriorityDTO> objtasktype1 = serializer1.Deserialize<List<TypeAndPriorityDTO>>(tasktype1);
                        
                        foreach (TypeAndPriorityDTO objtp in objtasktype1)
                            objtaskstatusdata2.Add(new SelectListItem { Text = objtp.Name, Value = objtp.ID.ToString() });
                        if (priority == 0)
                            objtaskstatusdata2.Insert(0, new SelectListItem { Text = "All", Value = "0", Selected = true });
                        else
                        {
                            objtaskstatusdata2.Insert(0, new SelectListItem { Text = "All", Value = "0", Selected = true });
                            objtaskstatusdata2.Find(x => x.Value == priority.ToString()).Selected = true;
                        }
                        objTask.PriorityDDL = objtaskstatusdata2;

                    }
                    
                    CustomResponse restype2 = APICalls.Get("GenericAPI/Get?type=2");
                    if (restype2.Response != null)
                    {
                        var tasktype = restype2.Response.ToString();
                        List<TypeAndPriorityDTO> objtasktype = serializer1.Deserialize<List<TypeAndPriorityDTO>>(tasktype);
                       
                        foreach (TypeAndPriorityDTO objtp in objtasktype)
                            objtasktypedata.Add(new SelectListItem { Text = objtp.Name, Value = objtp.ID.ToString() });
                        if (task_Type == 0)
                            objtasktypedata.Insert(0, new SelectListItem { Text = "All", Value = "0", Selected = true });
                        else
                        {
                            objtasktypedata.Insert(0, new SelectListItem { Text = "All", Value = "0", Selected = true });
                            objtasktypedata.Find(x => x.Value == task_Type.ToString()).Selected = true;
                        }
                        objTask.TypeDDL = objtasktypedata;

                    }
                    CustomResponse restype7 = APICalls.Get("GenericAPI/Get?type=3");
                    if (restype7.Response != null)
                    {
                        var tasktype1 = restype7.Response.ToString();
                        List<TypeAndPriorityDTO> objtasktype1 = serializer1.Deserialize<List<TypeAndPriorityDTO>>(tasktype1);
                        
                        foreach (TypeAndPriorityDTO objtp in objtasktype1)
                            objtaskstatusdata.Add(new SelectListItem { Text = objtp.Name, Value = objtp.ID.ToString() });
                        if (task_status == 0)
                            objtaskstatusdata.Insert(0, new SelectListItem { Text = "All", Value = "0", Selected = true });
                        else
                        {
                            objtaskstatusdata.Insert(0, new SelectListItem { Text = "All", Value = "0", Selected = true });
                            objtaskstatusdata.Find(x => x.Value == task_status.ToString()).Selected = true;
                        }
                        objTask.TaskStatusDDl = objtaskstatusdata;

                    }



                    objTask.ProjectsDDL = objprojects;

                    return objTask;
                }
                return null;
            }

            return null;
        }


        [HttpGet]
        public ActionResult Create()
        {

            if (TempData["Message"] != null)
                ViewBag.Message = TempData["Message"].ToString();
            
            return View(FillCreateTaskDropdowns());
        }

        [NonAction]
        private CreateTaskDTO FillCreateTaskDropdowns()
        
        {

            CreateTaskDTO objcreateTask = new CreateTaskDTO();
            List<SelectListItem> ObjDllData = new List<SelectListItem>();
            List<SelectListItem> ObjDllData1 = new List<SelectListItem>();
            List<SelectListItem> ObjDllData2 = new List<SelectListItem>();
            List<SelectListItem> ObjDllData3 = new List<SelectListItem>();
            List<SelectListItem> ObjDllData4 = new List<SelectListItem>();
            List<SelectListItem> ObjDllData5 = new List<SelectListItem>();
            CustomResponse restype1 = APICalls.Get("GenericAPI/Get?type=1");
            if (restype1.Response != null)
            {
                JavaScriptSerializer serializer1 = new JavaScriptSerializer();
                serializer1.MaxJsonLength = 1000000000;
                var uinfo = restype1.Response.ToString();
                List<TypeAndPriorityDTO> objprioroty = serializer1.Deserialize<List<TypeAndPriorityDTO>>(uinfo);
                ObjDllData.Add(new SelectListItem { Text = "Select Priority", Value = "" });
                foreach (TypeAndPriorityDTO objtp in objprioroty)
                    ObjDllData.Add(new SelectListItem { Text = objtp.Name, Value = objtp.ID.ToString() });
                objcreateTask.PriorityDDL = ObjDllData;


                CustomResponse restype2 = APICalls.Get("GenericAPI/Get?type=2");
                if (restype2.Response != null)
                {
                    var tasktype = restype2.Response.ToString();
                    List<TypeAndPriorityDTO> objtasktype = serializer1.Deserialize<List<TypeAndPriorityDTO>>(tasktype);
                    ObjDllData1.Add(new SelectListItem { Text = "Select User", Value = "" });
                    foreach (TypeAndPriorityDTO objtp in objtasktype)
                        ObjDllData1.Add(new SelectListItem { Text = objtp.Name, Value = objtp.ID.ToString() });
                    objcreateTask.TypeDDL = ObjDllData1;

                }
                CustomResponse restype3 = APICalls.Get("projectsapi/Get?projectid=0&userid=" + User.Identity.GetUserId());
                if (restype3.Response != null)
                {
                    var projects = restype3.Response.ToString();
                    List<ProjectDTO> projectsinfo = serializer1.Deserialize<List<ProjectDTO>>(projects);
                    ObjDllData2.Add(new SelectListItem { Text = "Select User", Value = "" });
                    foreach (ProjectDTO objtp in projectsinfo)
                        ObjDllData2.Add(new SelectListItem { Text = objtp.Name, Value = objtp.ID.ToString() });
                    objcreateTask.ProjectsDDL = ObjDllData2;

                }

                CustomResponse restype4 = APICalls.Get("UsersAPI/Get?type=1");
                if (restype4.Response != null)
                {
                    var assignees = restype4.Response.ToString();
                    List<UserDTO> usersdto = serializer1.Deserialize<List<UserDTO>>(assignees);
                    ObjDllData3.Add(new SelectListItem { Text = "Select User", Value = "" });
                    foreach (UserDTO objuser in usersdto)

Ticketing System.Mvc/Views/Tickets/Create.cshtml
@model Ticketing_System.Core.CreateTaskDTO
@{
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/PageLevel Scripts/Tasks.js"></script>
<script src="~/Scripts/bootstrap-datepicker.js"></script>

<div id="page-wrapper">
    <div class="col-lg-12">
        <h5 class="pull-right"> Dashboard - > Tickets ->Create Ticket</h5>
    </div>
    <script src="~/Scripts/validation.js"></script>
    <script src="~/Scripts/Validations.js"></script>
    <div class="row">
        <div class="col-lg-12">

            @using (Html.BeginForm("Create", "Tickets", FormMethod.Post, new { enctype="multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Create New Ticket</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="col-md-6">

                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.TextAreaFor(model => model.Description, 6, 47, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Project</label>
                            @*@Html.LabelFor(model => model.ProjectID, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9">
                                @* @Html.DropDownListFor(model => model.ProjectID,Model.ProjectsDDL, new { @class = "form-control" })*@
                                @Html.DropDownListFor(m => m.ProjectID, (IEnumerable<SelectListItem>)Model.ProjectsDDL, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ProjectID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Assigned To</label>
                            @*@Html.LabelFor(model => model.AssignedTo, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9">
                                @Html.DropDownListFor(m => m.AssignedTo, (IEnumerable<SelectListItem>)Model.AssignTODDL, new { @class = "form-control" })
                                @*  @Html.DropDownListFor(model => model.AssignedTo,  Model.AssignTODDL, new { @class = "form-control" })*@
                                @Html.ValidationMessageFor(model => model.AssignedTo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Reffered To</label>
                            @*@Html.LabelFor(model => model.RefereedTo, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9">
                                @Html.DropDownListFor(m => m.RefereedTo, (IEnumerable<SelectListItem>)Model.RefereerToDDL, new { @class = "form-control" })
                                @*   @Html.DropDownListFor(model => model.RefereedTo,  Model.RefereerToDDL, new { @class = "form-control" })*@
                                @Html.ValidationMessageFor(model => model.RefereedTo, "", new { @class = "text-danger" })
                            </div>
                        </div>


                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="control-label col-md-3">Due Date</label>
                            @*@Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9">
                                @Html.TextBoxFor(model => model.DueDate, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Assigned Date</label>
                            @*@Html.LabelFor(model => model.AssigndedDate, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9">
                                @Html.TextBoxFor(model => model.AssigndedDate, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.AssigndedDate, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3">Priority</label>
                            @*@Html.LabelFor(model => model.PriorityDDL, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9">
                                @Html.DropDownListFor(m => m.PriorityID, (IEnumerable<SelectListItem>)Model.PriorityDDL, new { @class = "form-control" })
                                @*   @Html.DropDownListFor(model => model.PriorityDDL,  Model.PriorityDDL, new { @class = "form-control" })*@
                                @Html.ValidationMessageFor(model => model.PriorityDDL, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Task Status</label>
                            @*@Html.LabelFor(model => model.Task_Status, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9">
                                @Html.DropDownListFor(m => m.Task_Status, (IEnumerable<SelectListItem>)Model.TaskStatusDDl, new { @class = "form-control" })
                                @*   @Html.DropDownListFor(model => model.PriorityDDL,  Model.PriorityDDL, new { @class = "form-control" })*@
                                @Html.ValidationMessageFor(model => model.Task_Status, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Task Type</label>
                            @*@Html.LabelFor(model => model.TypeID, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9">
                                @Html.DropDownListFor(m => m.TypeID, (IEnumerable<SelectListItem>)Model.TypeDDL, new { @class = "form-control" })
                                @*  @Html.DropDownListFor(model => model.TypeDDL, Model.TypeDDL, new { @class = "form-control" })*@
                                @Html.ValidationMessageFor(model => model.TypeDDL, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3">Upload screenshots</label>
                            @*@Html.LabelFor(model => model.Task_Status, htmlAttributes: new { @class = "control-label col-md-3" })*@
                            <div class="col-md-9" id="appendFileUpload">
                                <div class="row fileUploader" id="fileUploader">
                                    <div class="col-md-10">
                                        <input type="file" name="fileUpload" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button type="button" id="addFileUpload" class="btn btn-sm btn-default pull-right"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>
                        

                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-9">
                                <input type="submit" value="Create" class="btn btn-info btn-block" />
                                @if (ViewBag.Message != null)
                                {
                                    <label class="text-info">@ViewBag.Message</label>
                                }
                            </div>
                        </div>

                        
                    </div>


                </div>
            }

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {

        $('#DueDate,#AssigndedDate').datepicker({
            format: "mm/dd/yyyy"
        });

        
    });
</script>

Ticketing System.Mvc/Views/Tickets/ListAll.cshtml
@model Ticketing_System.Core.CreateTaskDTO
@{
  
}
 <!-- DataTables CSS -->
<link href="../bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" rel="stylesheet">
<!-- DataTables Responsive CSS -->
<link href="../bower_components/datatables-responsive/css/dataTables.responsive.css" rel="stylesheet">
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/PageLevel Scripts/Tasks.js"></script>
<div id="page-wrapper">
    <br />
    <div class="row">
            <div class="col-md-2">
                @Html.ActionLink("Create New", "Create", null, new {@class="btn btn-info" })
    </div>
        <div class="col-md-2">
            @Html.DropDownList("ddlproject", (IEnumerable<SelectListItem>)Model.ProjectsDDL, new { @class = "form-control" })
            </div>
        <div class="col-md-2">
            @Html.DropDownList("ddlpriority", (IEnumerable<SelectListItem>)Model.PriorityDDL, new { @class = "form-control" })
        </div>
        <div class="col-md-2">
            @Html.DropDownList("ddltasktype", (IEnumerable<SelectListItem>)Model.TypeDDL, new { @class = "form-control" })
        </div>
        <div class="col-md-2">
            @Html.DropDownList("ddltaskstatus", (IEnumerable<SelectListItem>)Model.TaskStatusDDl, new { @class = "form-control" })
        </div>
        <div class="col-md-2">
            <input type="button" id="btnFilterTasks" class="btn btn-info" value="Filter Tasks" />

        </div>
        </div>
    
    <div class="row">
        <div class="col-lg-12">
           
            <div class="panel-body">
                <div class="row text-info">
                    @if (ViewBag.Message != null)
                    {
                        <label>@ViewBag.Message</label>
                    }
                </div>
 

                <div class="dataTable_wrapper">
                    <table id="dataTables-example" class="table table-striped table-bordered table-hover dataTable no-footer" role="grid" aria-describedby="dataTables-example_info">
                        <thead>
                            <th>
                                Task ID
                            </th>
                        <th>
                            Name
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Assigned Date
                        </th>
                        <th>
                            Priority
                        </th>
                        <th>
                          Task  Status
                        </th>
                        <th>
                            Task  Type
                        </th>
                        <th>Assigned To</th>
                        <th></th>
                        </thead>

                        @foreach (var item in Model.TasksDTO)
                        {
                            <tr>
                                <td>

                                    @item.TaskDisplayName
                                </td>
                                <td>

                                  @item.Title
                                </td>
                                <td>
                                    @item.Description
                                </td>
                                <td>
                                    @item.AssigndedDate
                                </td>
                                <td>
                                    @item.PriorityName
                                </td>
                                <td>
                                    @item.Task_Status_Name
                                </td>
                                <td>
                                    @item.Task_Type_Name
                                </td>
                                <td>
                                    @item.AssignedToName
                                </td>
                                <td>
                                    @Html.ActionLink("View", "Edit", new { ticketid = item.ID }, new { @class = "btn btn-info btn-block" }) 
                                    @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- jQuery -->
<script src="../bower_components/jquery/dist/jquery.min.js"></script>



<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true
        });

    });
</script>